local/ARM: EXYNOS: Fix conflicts with Exynos PMU in drivers/soc/samsung
The ARMv7 Exynos cannot be build because of several errors related
to duplicate definitions of Exynos PMU symbols:

drivers/built-in.o: In function `combiner_handle_cascade_irq':
drivers/irqchip/exynos-combiner.c:81: multiple definition of `pmu_base_addr'
arch/arm/mach-exynos/built-in.o:arch/arm/mach-exynos/pmu.c:50: first defined here
drivers/built-in.o: In function `exynos_sys_powerdown_conf':
drivers/soc/samsung/exynos-pmu.c:32: multiple definition of `exynos_sys_powerdown_conf'
arch/arm/mach-exynos/built-in.o:arch/arm/mach-exynos/pmu.c:749: first defined here

Limit the new EXYNOS_PMU driver to ARM64 architecture.

Signed-off-by: Krzysztof Kozlowski <k.kozlowski@samsung.com>